# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19a31d47b79ab80041fdd52b49bc826ded25c12e2858fc1a2963fecd1961ee7f8e59347ee6f49c56a6412c723a66370e4fae90b09be648514eef42aa1997fd0c

test:
  secret_key_base: 43ec392df8b2e752bd8484608d4e610bab59def46dc40df5d1a44c286828f8b37eae3e796a1713a4137bd1d40cd98e6776c4a9970933dc99347e67f54257e5b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
